name: Faleh_Hafez
description: A new Flutter project.

publish_to: "none" 

version: 0.1.4+5

environment:
  sdk: ">=3.2.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  hive_flutter: ^1.1.0
  flutter_chat_ui: ^1.6.10
  uuid: ^3.0.5
  file_picker: ^7.0.2
  open_file: ^3.0.3
  http: ^0.13.0
  flash: ^3.1.1
  timeago: ^3.7.0
  # dartz: ^0.10.1
  # google_fonts: ^6.2.1
  get_it: ^7.6.0
  dio: ^5.7.0
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  # syncfusion_flutter_pdfviewer: ^20.4.54
  shared_preferences: ^2.0.0
  path_provider: ^2.1.4
  local_auth: ^2.1.8
  flutter_secure_storage: ^4.2.1
  persian: ^1.1.1
  dartz: ^0.10.1
  encrypt: ^5.0.3
  signalr_core: ^1.1.0
  flutter_slidable: ^3.1.2
  android_intent_plus: ^3.0.1
  voice_message_package: ^2.1.1
  swipe_to: ^1.0.6
  animated_theme_switcher: ^2.0.6
  flutter_sound: ^9.2.13
  just_audio: ^0.9.42
  record: ^5.0.5
  audioplayers: ^4.1.0
  # json_annotation: ^4.8.1
  # get_it: ^7.6.0dependencies:
  package_info_plus: ^4.2.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/main_logo_faal.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1
  build_runner: ^2.4.6
  # json_serializable: ^6.7.1

  flutter_lints: ^3.0.2

flutter:
  
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/icon/
    - assets/fonts/
  

  fonts:
    - family: iranNastaliq
      fonts:
        - asset: assets/fonts/IranNastaliq.ttf

    - family: iranSans
      fonts:
        - asset: assets/fonts/IRANSansWeb_Bold.ttf

    - family: lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf

    - family: vazir
      fonts:
        - asset: assets/fonts/Vazir-Bold.ttf
 
  
